In [3]:
# Bài tập 1
import numpy as np
matrix = np.random.rand(3, 3)
print("Ma trận 3x3 với các phần tử ngẫu nhiên:\n", matrix )

Ma trận 3x3 với các phần tử ngẫu nhiên:
 [[0.51525189 0.98287176 0.06279705]
 [0.01459517 0.29180225 0.75571567]
 [0.99881158 0.60519654 0.95490401]]


In [4]:
# bài tập 2 phép cộng ma trận
matrix1 = np.random.rand(3,3)
matrix2 = np.random.rand(3,3)

matrix_sum = matrix1 + matrix2
print('Tổng của hai ma trận:\n', matrix_sum)

Tổng của hai ma trận:
 [[0.97712258 1.77267332 0.387807  ]
 [1.04612023 1.27071386 0.92225719]
 [0.52275849 1.17828655 1.44329986]]


In [5]:
#Bài tập 3 Phép nhân ma trận
matrix1 = np.random.rand(3,3)
matrix2 = np.random.rand(3,3)

matrix_product = np.dot(matrix1,matrix2)
print("Tích của hai ma trận:\n", matrix_product)

Tích của hai ma trận:
 [[0.89196382 0.59444769 0.36000581]
 [1.33293485 0.93717603 0.43758729]
 [0.67229848 0.47455623 0.35046125]]


In [6]:
#Bài tập 4: Ma trận chuyển vị
matrix = np.random.rand(3,3)

maxtrix_transpose = np.transpose(matrix)
print('Ma trận chuyển vị: \n', maxtrix_transpose)

Ma trận chuyển vị: 
 [[0.66098697 0.54141132 0.30663874]
 [0.79508978 0.36914628 0.50238306]
 [0.2650635  0.31311362 0.9239455 ]]


In [7]:
#Bài tập 5: Ma trận nghịch đảo
matrix = np.random.rand(3,3)

try:
    matrix_inverse = np.linalg.inv(matrix)
    print("Ma trận nghịch đảo: \n", matrix_inverse)
except np.linalg.LinAlgError:
    print("Ma trận không có nghịch đảo")

Ma trận nghịch đảo: 
 [[ -0.9768143  -11.25392225   9.15249442]
 [ -0.48801219   1.45141143   0.05828281]
 [  2.24266425   7.14671629  -6.37489234]]


In [8]:
#Bài tập 6 Tính định thức ma trận
matrix = np.random.rand(3,3)

det = np.linalg.det(matrix)
print('Định thức của ma trận: \n', det)

Định thức của ma trận: 
 -0.19267039321105275
