In [5]:
#1 Nhân ma trận
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.einsum('ij,jk->ik',A,B)
print(C)

#2 Tính tổng các phần tử trong một mảng
a = np.array([1,2,3,4])
sum_a = np.einsum('i->', a)
print(sum_a)

#3 Nhân chéo (Outer product)
a = np.array([1,2,3])
b = np.array([4,5,6])
outer_product = np.einsum('i,j->ij', a, b)
print(outer_product)

[[19 22]
 [43 50]]
10
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [8]:
#Bài tập 1: Tính tổng các cột trong ma trận
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_sum = np.einsum('ij->j', A)
print(column_sum)

[12 15 18]


In [9]:
#Bài tập 3 Tính tổng các phần tử trên đường chéo chính
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
diagonal_sum = np.einsum('ii->',A)
print(diagonal_sum)

15


In [10]:
#Bài tập 4 Nhân hai ma trận 2D
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.einsum('ij,jk->ik',A,B)
print(C)

[[19 22]
 [43 50]]


In [11]:
#Bài 5 Tính tích ngoài của 2 vector
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
outer_product = np.einsum('i,j->ij',a,b)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [13]:
#Bài tập 6 Tính ma trận Gram của một tensor 3D
import numpy as np

def gram_matrix(tensor):
    channels, height, width = tensor.shape
    features = tensor.reshape(channels, height * width)
    gram = np.einsum('ik,jk->ij',features,features)
    return gram

tensor = np.random.rand(3,4,4)
gram = gram_matrix(tensor)
print(gram)

[[5.82508009 3.67115016 4.24728743]
 [3.67115016 4.73641367 3.23752909]
 [4.24728743 3.23752909 4.25813012]]
